### ISSUE TITLE
deployment slot

### ISSUE THREAD

**Issue by acb122** [felixrieseberg/Ghost-Azure#17]
hi,
When trying to use this with azure and then creating a deployment slot and copying production it does not work, just gets an internal error. any ideas how to set this up.

**Comment by felixrieseberg** [comment]
Hey, without the actual error, there's little I can do to help you. Could you go and check? You should find it in the iisnode folder of your Ghost deployment. Quick tutorial on how to get there:

1) YOURDOMAIN.scm.azurewebsites.net
2) Go to the debug console
3) `cd` into your Ghost folder
4) Find the `iisnode` folder with logs there

**Comment by acb122** [comment]
thanks for getting back to me.

ERROR: casper cannot be activated because it is not currently installed. 

 Error
    at Error.ValidationError (D:\home\site\wwwroot\core\server\errors\validation-error.js:6:18)
    at then (D:\home\site\wwwroot\core\server\data\validation\index.js:120:35)
    at tryCatcher (D:\home\site\wwwroot\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (D:\home\site\wwwroot\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (D:\home\site\wwwroot\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (D:\home\site\wwwroot\node_modules\bluebird\js\main\promise.js:245:10)
    at Async._drainQueue (D:\home\site\wwwroot\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (D:\home\site\wwwroot\node_modules\bluebird\js\main\async.js:133:10)
    at Async.drainQueues (D:\home\site\wwwroot\node_modules\bluebird\js\main\async.js:15:14)
    at process._tickDomainCallback (node.js:463:13) 

this is the file i have done npm install so is weird that it cant find casper

**Comment by felixrieseberg** [comment]
Could you try installing again? Clearly, something went wrong.
