### ISSUE TITLE
SqlLite3 doesn't install correctly

### ISSUE THREAD

**Issue by mjhilton** [felixrieseberg/Ghost-Azure#19]
Hi there,

I've just installed from the Azure Marketplace (twice - deleted and recreated), and am getting a 500 error. I waited for deployment to complete, gave it some time, and then hit the site - 500. Let it sit for another 5 minutes or so in case install was still going; same problem.

Logs:

```
[31m
ERROR:[39m [31mCannot find module 'D:\home\site\wwwroot\node_modules\sqlite3\lib\binding\node-v46-win32-ia32\node_sqlite3.node'[39m 

 Error: Cannot find module 'D:\home\site\wwwroot\node_modules\sqlite3\lib\binding\node-v46-win32-ia32\node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17) 
```

I notice that it's looking for `node_sqlite3.node` under a `node-v46-win32-ia32` directory, but when exploring in Kudu, I can see that the directory is actually v11: `D:\home\site\wwwroot\node_modules\sqlite3\lib\binding\node-v11-win32-ia32`

**Comment by mjhilton** [comment]
Whoops. I'd assumed the Azure Marketplace template and this deployment repo were one and the same. They're not.

Tried again via the "Deploy to Azure" button in the readme, and all worked well.
